/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface:                  '#10141a',
        'surface-dim':            '#10141a',
        'surface-bright':         '#353940',
        'surface-container-lowest': '#0a0e14',
        'surface-container-low':  '#181c22',
        'surface-container':      '#1c2026',
        'surface-container-high': '#262a31',
        'surface-container-highest': '#31353c',
        'surface-variant':        '#31353c',
        'surface-tint':           '#d2bbff',
        'on-surface':             '#dfe2eb',
        'on-surface-variant':     '#ccc3d8',
        'inverse-surface':        '#dfe2eb',
        'inverse-on-surface':     '#2d3137',
        outline:                  '#958da1',
        'outline-variant':        '#4a4455',
        primary:                  '#d2bbff',
        'on-primary':             '#3f008e',
        'primary-container':      '#7c3aed',
        'on-primary-container':   '#ede0ff',
        'inverse-primary':        '#732ee4',
        'primary-fixed':          '#eaddff',
        'primary-fixed-dim':      '#d2bbff',
        secondary:                '#adc6ff',
        'on-secondary':           '#002e6a',
        'secondary-container':    '#0566d9',
        'on-secondary-container': '#e6ecff',
        'secondary-fixed':        '#d8e2ff',
        'secondary-fixed-dim':    '#adc6ff',
        tertiary:                 '#4edea3',
        'on-tertiary':            '#003824',
        'tertiary-container':     '#007650',
        'on-tertiary-container':  '#76ffc2',
        'tertiary-fixed':         '#6ffbbe',
        'tertiary-fixed-dim':     '#4edea3',
        error:                    '#ffb4ab',
        'on-error':               '#690005',
        'error-container':        '#93000a',
        'on-error-container':     '#ffdad6',
        background:               '#10141a',
        'on-background':          '#dfe2eb',
      },
      fontFamily: {
        sans:  ['Inter', 'system-ui', 'sans-serif'],
        mono:  ['JetBrains Mono', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display':     ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':     ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-md':     ['14px', { lineHeight: '1.6', fontWeight: '450' }],
        'code-sm':     ['12px', { lineHeight: '1.6', fontWeight: '450' }],
        'label-caps':  ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'margin': '24px',
      },
    },
  },
  plugins: [],
}
